import Foundation
import os.log

private let log = SpecchioLogger.autoLaunch

struct WDABuildCache {

    /// Root cache directory: ~/Library/Application Support/Specchio/WDABuild/
    static var cacheDirectory: URL {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        return appSupport.appendingPathComponent("Specchio/WDABuild", isDirectory: true)
    }

    /// The derivedData path xcodebuild will write to
    static var derivedDataPath: URL {
        cacheDirectory.appendingPathComponent("DerivedData", isDirectory: true)
    }

    private static var cacheKeyFile: URL {
        cacheDirectory.appendingPathComponent("cache_key.txt")
    }

    /// Path to bundled WDA source inside the app bundle
    static var bundledWDAProjectPath: String? {
        guard let resourcePath = Bundle.main.resourcePath else { return nil }
        let projectPath = (resourcePath as NSString).appendingPathComponent("WebDriverAgent/WebDriverAgent.xcodeproj")
        guard FileManager.default.fileExists(atPath: projectPath) else { return nil }
        return projectPath
    }

    /// Finds the .xctestrun file generated by build-for-testing
    static func findXCTestRun() -> URL? {
        let buildDir = derivedDataPath.appendingPathComponent("Build/Products")
        guard FileManager.default.fileExists(atPath: buildDir.path) else { return nil }

        guard let contents = try? FileManager.default.contentsOfDirectory(
            at: buildDir,
            includingPropertiesForKeys: nil
        ) else { return nil }

        return contents.first { $0.pathExtension == "xctestrun" }
    }

    /// Checks whether cached artifacts are still valid
    static func isCacheValid() -> Bool {
        guard findXCTestRun() != nil else {
            log.info("WDABuildCache: no .xctestrun found — cache invalid")
            return false
        }

        guard let currentKey = computeCacheKey(),
              let storedKey = try? String(contentsOf: cacheKeyFile, encoding: .utf8),
              storedKey.trimmingCharacters(in: .whitespacesAndNewlines) == currentKey else {
            log.info("WDABuildCache: cache key mismatch — cache invalid")
            return false
        }

        log.info("WDABuildCache: cache is valid")
        return true
    }

    /// Writes the current cache key to disk after a successful build
    static func writeCacheKey() {
        guard let key = computeCacheKey() else { return }
        try? FileManager.default.createDirectory(at: cacheDirectory, withIntermediateDirectories: true)
        try? key.write(to: cacheKeyFile, atomically: true, encoding: .utf8)
        log.info("WDABuildCache: wrote cache key")
    }

    /// Removes all cached artifacts — next connect will do a full rebuild
    static func invalidate() {
        log.info("WDABuildCache: invalidating cache")
        try? FileManager.default.removeItem(at: cacheDirectory)
    }

    /// Removes only DerivedData (keeps build log intact for multi-team diagnostics).
    static func clearDerivedData() {
        let dd = derivedDataPath
        guard FileManager.default.fileExists(atPath: dd.path) else { return }
        log.info("WDABuildCache: clearing DerivedData only (preserving build log)")
        try? FileManager.default.removeItem(at: dd)
    }

    /// Path to the persisted build log
    static var buildLogPath: URL {
        cacheDirectory.appendingPathComponent("build_log.txt")
    }

    /// Appends a line to the persisted build log
    static func appendBuildLog(_ line: String) {
        try? FileManager.default.createDirectory(at: cacheDirectory, withIntermediateDirectories: true)
        let data = (line + "\n").data(using: .utf8) ?? Data()
        if FileManager.default.fileExists(atPath: buildLogPath.path) {
            if let handle = try? FileHandle(forWritingTo: buildLogPath) {
                handle.seekToEndOfFile()
                handle.write(data)
                handle.closeFile()
            }
        } else {
            try? data.write(to: buildLogPath)
        }
    }

    /// Reads the persisted build log (last N lines)
    static func readBuildLog(last lines: Int = 200) -> String {
        guard let content = try? String(contentsOf: buildLogPath, encoding: .utf8) else { return "" }
        let all = content.components(separatedBy: "\n").filter { !$0.isEmpty }
        let start = max(0, all.count - lines)
        return all[start...].joined(separator: "\n")
    }

    /// Clears the persisted build log at the start of a new build
    static func clearBuildLog() {
        try? FileManager.default.removeItem(at: buildLogPath)
    }

    // MARK: - Private

    static func computeCacheKey() -> String? {
        guard let xcodeVersion = xcodeVersion() else { return nil }
        let wda = wdaVersion()
        let team = UserDefaults.standard.string(forKey: "selectedTeamID") ?? "unknown"
        let key = "xcode:\(xcodeVersion)|wda:\(wda)|team:\(team)"
        return key
    }

    private static func xcodeVersion() -> String? {
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/xcodebuild")
        proc.arguments = ["-version"]
        let pipe = Pipe()
        proc.standardOutput = pipe
        proc.standardError = Pipe()
        try? proc.run()
        proc.waitUntilExit()

        let data = pipe.fileHandleForReading.readDataToEndOfFile()
        guard let output = String(data: data, encoding: .utf8) else { return nil }
        return output.components(separatedBy: "\n")
            .filter { !$0.isEmpty }
            .joined(separator: "-")
    }

    private static func wdaVersion() -> String {
        guard let projectPath = bundledWDAProjectPath else { return "unknown" }
        let wdaRoot = (projectPath as NSString).deletingLastPathComponent
        let versionFile = (wdaRoot as NSString).appendingPathComponent(".wda_version")
        if let version = try? String(contentsOfFile: versionFile, encoding: .utf8)
            .trimmingCharacters(in: .whitespacesAndNewlines), !version.isEmpty {
            return version
        }
        // Fallback: use modification date of the project
        if let attrs = try? FileManager.default.attributesOfItem(atPath: projectPath),
           let modDate = attrs[.modificationDate] as? Date {
            return String(Int(modDate.timeIntervalSince1970))
        }
        return "unknown"
    }
}
